### PR TITLE
feat(metamorpheus): Create converter from Metamorpheus to core MSstats

### PR DESCRIPTION
**Pull request by tonywu1999**
# Motivation and Context

As a part of this [issue](https://github.com/Vitek-Lab/MSstatsPTM/issues/48), users are requesting a converter from Metamorpheus to MSstatsPTM.  The first step is to create a converter from Metamorpheus to core MSstats.

I'm placing a new converter in MSstatsConvert instead of MSstats because long term, converters should be in MSstatsConvert for the following reasons:
- **Scalability**: Every time a new upstream tool is introduced, multiple packages need to be modified to create a new converter.  This setup is  confusing for those who do not maintain the suite of MSstats packages but want to contribute.  As a result, rather than the open source community creating converters right now, we need maintainers to create the converters.
- **Timing Releases**: Since multiple packages need to be modified, we must release packages to bioconductor in a particular order.  We need to keep track of order of releases of multiple packages (i.e. MSstatsConvert first, MSstats next, etc.), otherwise new features could be broken without us knowing.  While it's easy to keep track right now, it's not as easy to keep track if MSstats expands to the point where multiple features are being built at the same time.

## Changes

- Created a new converter called MetamorpheusToMSstatsFormat in MSstatsConvert.  
- Added a .sharedParametersAmongConverters function to store shared parameters amongst all converters

## Testing

- Added unit test to test basic functionality of MetamorpheusToMSstatsFormat

## Checklist Before Requesting a Review
- [x] I have read this repository's [contributing guidelines](https://github.com/Vitek-Lab/MSstatsConvert/blob/master/.github/CONTRIBUTING.md)
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mstaniak** [comment]
This function should be in MSstats package (defined there in converters.R file).

**Comment by mstaniak** [comment]
MSstatsConvert contains MSstatsClean method for relevant file type, MSstats uses that + general functions like MSstatsPreprocess to define converters.

**Comment by mstaniak** [comment]
Let me know if you need a clarification on this convention

**Comment by tonywu1999** [comment]
Cancelling in favor of https://github.com/Vitek-Lab/MSstats/pull/109.  Long term, we will reconsider moving all converters to MSstatsConvert for scalability purposes.  For now, will stick with the current patterns for backwards compatibility.

**Review by devonjkohler — APPROVED** [review]

**Comment by mstaniak** [comment]
A function like .sharedParametersAmongConverters exists in MSstats currently, let's keep this in mind while moving converter later.

**Review by mstaniak — APPROVED** [review]

**Pull request merged**
